name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: Run merge script
        uses: klay-ke/auto-merge-pr@master
        id: merge-pr
        with:
          send-to-dingtalk-group: true
          dingtalk-access-token: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          dingtalk-secret: ${{ secrets.DINGTALK_SECRET }}
          maintainer-team-name: ${{ secrets.MAINTAINER_TEAM_NAME }}
          gh-token: ${{ secrets.GH_TOKEN }}
          ci-command: 'bash ./build.sh'
